config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # read all restaurants
  resources :restaurants
  # get 'restaurants', to: 'restaurants#index'
  # # read each individual restaurant
  # get 'restaurants/:id', to: 'restaurants#show'
  # # create a restaurant
  # get 'restaurants/new', to: 'restaurants#new'
  # post 'restaurants', to: 'restaurants#create'
  # # update a restaurant
  # get 'restaurants/:id/edit', to: 'restaurants#edit'
  # put 'restaurants/:id', to: 'restaurants#update'
  # patch 'restaurants/:id', to: 'restaurants#update'
  # # delete a restaurant
  # delete 'restaurants/:id', to: 'restaurants#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :rating, inclusion: { in: (0..5) }
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurants_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.save(restaurants_params)
      redirect_to restaurants_path
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurants_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ModelsAndCrud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_restaurant_form.html.erb
<%= form_for restaurant do |f| %>
  <%= f.label 'Name' %>
  <%= f.text_field :name %>
  <%= f.label 'Rating' %>
  <%= f.text_field :rating %>
  <%= f.label 'Address' %>
  <%= f.text_field :address %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'restaurant_form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<% @restaurants.each do |restaurant| %>
  <%= link_to restaurant_path(restaurant) do %>
    <h2><%= restaurant.name %></h2>
  <% end %>
  <p><%= "* " * restaurant.rating %></p>
  <p><%= restaurant.address %></p>
  <hr>
<% end %>

app/views/restaurants/new.html.erb
<%= render 'restaurant_form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= "* " * @restaurant.rating %></p>
<p><%= @restaurant.address %></p>
<%= link_to 'Delete', restaurant_path, method: :delete, data: { confirm: 'are you sure?' } %>
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
<%= link_to 'Back to restaurants', restaurants_path %>